#!/bin/bash

shopt -s nocasematch

files=$(find . -maxdepth 1 -type f -iname "gh01*.mp4")

for file in $files; do
  echo "Processing $file"

  if [[ "$file" =~ gh([0-9]{2})([0-9]{4})\.mp4$ ]]; then
    clipId=${BASH_REMATCH[2]}

    clipFiles=$(find . -maxdepth 1 -type f -iname "gh??$clipId.mp4")
    clipCount=$(echo "$clipFiles" | wc -l)
    outputFile="combined-$clipId.mp4"

    if [[ "$clipCount" -gt 1 ]]; then
      ffmpeg -f concat -safe 0 \
        -i <(for f in $clipFiles; do echo "file '$PWD/$f'"; done) \
        -c copy \
        -map 0:v -map 0:a -map 0:3 -tag:2 gpmd \
        $outputFile

      echo "-> Combined $file to $outputFile"
    else
      echo "-> No need to combine"
    fi
  fi
done
